"""Contains misc useful functions.
"""
import string
import random
import re
from datetime import timedelta

from .. import CONFIG


def strip_steam_id(identity_url):
    """Returns the user's Steam_ID from their identity URL.

    :param identity_url: The Steam URL of the player
    """
    steam_id_re = re.compile('steamcommunity.com/openid/id/(.*?)$')
    match = steam_id_re.search(identity_url)
    return match.group(1)


def random_str(length=32):
    """Generate a random string consisting of upper and lower case letters and numbers and with
    the given length.

    :param length: Number of characters the string should be. Default is 32
    :return: Randomly generated string
    """
    chars = string.ascii_uppercase + string.ascii_lowercase + string.digits
    return ''.join(random.SystemRandom().choice(chars) for _ in range(length))


def strip_tags(name):
    """Strips tags generated by Arma's integration with squad XMLs

    :param name: String representing the full name extracted from Steam server query API
    :return: String with only the player's name and not the tag
    """
    re_tag = '\s\[.+\]$'
    name = re.sub(re_tag, '', name)
    return name.strip()


def convert_to_utc(dt):
    """Converts given datetime from appropriate timezone based on config value.
    Used to convert user datetime object to UTC time zone

    :param dt: Datetime object to mutate
    :return: Datetime object corrected for timezone
    """
    return dt - timedelta(hours=CONFIG['TIMEZONE'])


def convert_from_utc(dt):
    """Converts given datetime to appropriate timezone based on config value.
    Used to convert db datetime object to local time zone

    :param dt: Datetime object to mutate
    :return: Datetime object corrected for timezone
    """
    return dt + timedelta(hours=CONFIG['TIMEZONE'])