repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      # See https://pre-commit.com/hooks.html for more hooks
      - id: check-yaml
        exclude: "[a-zA-Z]*/(cassettes)/(.)*"
      - id: check-ast
      - id: check-case-conflict
        exclude: "[a-zA-Z]*/(cassettes)/(.)*"
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        exclude: "[a-zA-Z]*/(migrations)/(.)*"

  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
        exclude: "[a-zA-Z]*/(migrations)/(.)*"

  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          [
            "flake8-bugbear",
            "flake8-comprehensions",
            "flake8-mutable",
            "flake8-print",
            "flake8-simplify",
          ]

  - repo: https://github.com/pycqa/bandit
    rev: 1.7.0
    hooks:
      - id: bandit
        args: ["-iii", "-ll"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.930"
    hooks:
      - id: mypy
        exclude: "[a-zA-Z]*/(migrations)/(.)*"
        additional_dependencies:
          [
            "django-stubs",
            "environs",
            "rich",
            "django-allauth",
            "psycopg2",
          ]
          # djangorestframework-stubs
