repos:
  - repo: local
    hooks:
      ## lib/environment hooks

      - id: lib-environment-black
        name: black on lib-environment
        stages: [commit]
        language: docker_image
        types: [python]
        files: ^lib/environment/
        entry: lib.environment black
        args: [--config, /srv/app/pyproject.toml]

      - id: lib-environment-flake8
        name: flake8 on lib-environment
        stages: [commit]
        language: docker_image
        types: [python]
        files: ^lib/environment/
        entry: lib.environment flake8
        args: [--config, /srv/app/.flake8]

      - id: lib-environment-mypy
        name: Mypy on lib-environment
        stages: [commit]
        language: docker_image
        types: [python]
        files: ^lib/environment/
        entry: lib.environment mypy
        args: [--config-file, /srv/app/mypy.ini]
