default_language_version:
  python: python3.9
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      # See https://pre-commit.com/hooks.html for more hooks
      - id: check-ast
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pycqa/isort
    rev: 5.9.1
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 21.6b0
    hooks:
      - id: black
        name: black (for lib.environment)
        files: ^lib/environment/
        args: [--config, lib/environment/pyproject.toml]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        name: flake8 (for lib.environment)
        files: ^lib/environment/
        args: [--config, lib/environment/setup.cfg]
        additional_dependencies:
          [
            "flake8-bugbear",
            "flake8-comprehensions",
            "flake8-mutable",
            "flake8-print",
            "flake8-simplify",
          ]

  - repo: https://github.com/pycqa/bandit
    rev: 1.7.0
    hooks:
      - id: bandit
        args: ["-iii", "-ll"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.910"
    hooks:
      - id: mypy
        name: mypy (for lib.environment)
        files: ^lib/environment/
        args: [--config-file, lib/environment/mypy.ini]
        #exclude: "[a-zA-Z]*/(migrations)/(.)*"
        # additional_dependencies: [
        #     # mypy dependencies
        #     # djangorestframework-stubs,
        #     # django-stubs,
        #     # runtime dependencies
        #     ...,
        #   ]
