web:
  working_dir: /opt/web_dev
  volumes:
     - /c/Users/adam/Dropbox/Projects/arma/zas/web:/opt/web_dev
  #command: --reload --access-logfile "-" --error-logfile "-" --log-level debug
  entrypoint: python run.py

mongo-express:
  image: knickers/mongo-express
  links:
    - mongo
  ports:
    - "8081:8081"