web:
  build: ./web
  expose:
    - "8000"
  links:
    - mongo
  volumes:
    - /opt/web/app/static
    - /c/Users/adam/zas/config/zas.cfg:/etc/zas/zas.cfg:ro
    - /c/Users/adam/zas/logs/web:/var/log/web
  environment:
    - ZAS_CONFIG=/etc/zas/zas.cfg
  command: gunicorn -b :8000 run:app --access-logfile "/var/log/web/gunicorn_access.log" --error-logfile "/var/log/web/gunicorn_error.log"
  restart: always

nginx:
  image: nginx
  ports:
    - "80:80"
  links:
    - web
  volumes:
    - /c/Users/adam/zas/config/nginx.conf:/etc/nginx/nginx.conf:ro
    - /c/Users/adam/zas/logs/nginx:/var/log/nginx
  volumes_from:
    - web:ro
  restart: always

dbdata:
  image: ubuntu
  volumes:
    - /data/db
  command: /usr/bin/tail -f /dev/null
  restart: always

mongo:
  image: mongo
  expose:
    - "27017"
  volumes:
    - /c/Users/adam/zas/config/mongod.yml:/etc/zas/mongod.yml:ro
    - /c/Users/adam/zas/logs/mongodb:/var/log/mongodb
  volumes_from:
    - dbdata
  command: -f /etc/zas/mongod.yml
  restart: always