web:
  build: ./web
  expose:
    - "8000"
  links:
    - mongo
  volumes:
    - /opt/web/app/static
  environment:
    - ZAS_CONFIG=/etc/zas/zas.cfg
  command: --access-logfile "/var/log/web/gunicorn_access.log" --error-logfile "/var/log/web/gunicorn_error.log"
  restart: always

nginx:
  image: nginx
  ports:
    - "80:80"
  links:
    - web
  volumes_from:
    - web:ro
  restart: always

backup:
  build: ./backup
  volumes_from:
    - dbdata:ro
  restart: always

mongo:
  image: mongo
  expose:
    - "27017"
  volumes_from:
    - dbdata
  command: -f /etc/zas/mongod.yml
  restart: always

dbdata:
  image: ubuntu
  volumes:
    - /data/db
  command: /usr/bin/tail -f /dev/null
  restart: always