web:
  build: ./web
  expose:
    - "8000"
  links:
    - mongo
  volumes:
    - /opt/web/app/static

nginx:
  image: nginx
  ports:
    - "80:80"
  links:
    - web
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  volumes_from:
    - web:ro

dbdata:
  image: ubuntu
  volumes:
    - /data/db
  command: /usr/bin/tail -f /dev/null

mongo:
  image: mongo
  expose:
    - "27017"
  volumes_from:
    - dbdata