version: "3.7"
services:
    zas_back: 
        build: ./zas_back
        ports:
            - "80:8000"
        depends_on:
            - postgres

    postgres:
        image: postgres:latest
        ports:
            - "${ZAS_POSTGRES_PORT}:5432"
        volumes:
            - "zasdevdb:/var/lib/postgresql/data:rw"
        environment:
            POSTGRES_DB: "${ZAS_POSTGRES_DB_NAME}"
            POSTGRES_USER: "${ZAS_POSTGRES_DB_USER}"
            POSTGRES_PASSWORD: "${ZAS_POSTGRES_DB_PASSWORD}"

volumes:
    zasdevdb: