web:
  volumes:
    - /etc/zas/zas.cfg:/etc/zas/zas.cfg:ro
    - /var/zas/log/web:/var/log/web

mongo-express:
  env_file: /etc/zas/mongo-express.env

nginx:
  ports:
    - "443:443"
  volumes:
    - /etc/zas/nginx.conf:/etc/nginx/nginx.conf:ro
    - /var/zas/log/nginx:/var/log/nginx
    - /etc/letsencrypt:/etc/letsencrypt:ro

backup:
  volumes:
    - /etc/zas/backup_config.py:/opt/backup/backup_config.py:ro
    - /var/zas/log/backup:/var/log/backup

mongo:
  volumes:
    - /etc/zas/mongod.yml:/etc/mongod/mongod.yml:ro
    - /var/zas/log/mongodb:/var/log/mongodb
