restore:
  volumes:
  #  - /c/Users/adam/zas/config/restore_config.py:/opt/restore/restore_config.py:ro
    - /home/adam/zas/config/restore_config.py:/opt/restore/restore_config.py:ro
  #  - /c/Users/adam/zas/log/restore:/var/log/restore
    - /home/adam/zas/log/restore:/var/log/restore
