name: lib-environment-test

on:
  pull_request:
    paths:
      - "lib/environment/**"

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        # Issue: https://github.com/docker/build-push-action/issues/286
        uses: docker/setup-buildx-action@master
        with:
          install: true

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          # Key is named differently to avoid collision
          key: ${{ runner.os }}-lib-environment-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-lib-environment-buildx

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-lib-environment-pip }}

      - name: Install pre-commit
        run: |
          python -m pip install pre-commit
          pre-commit install

      - name: Run pre-commit
        run: |
          make pre-commit-lib-environment

      - name: build
        run: |
          docker build -t lib.environment --cache-from type=local,src=/tmp/.buildx-cache --cache-to type=local,mode=max,dest=/tmp/.buildx-cache-new lib/environment/.

      - name: test
        run: |
          make test-lib-environment

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
